"""add blacklisted table

Revision ID: ba9a813e7a84
Revises: deea78008394
Create Date: 2026-02-19 19:01:32.212877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9a813e7a84'
down_revision: Union[str, Sequence[str], None] = 'deea78008394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_id'))

    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
